name: cellwall_analysis
channels:
   - conda-forge
   - defaults
dependencies:
   - python=3.10.12
   - tifffile=2023.8.30
   - pillow=10.0.0
   - pandas=2.0.1
   - numpy=1.25.2
   - matplotlib=3.7.2
   - sqlite3=3.41.2
   - scipy=1.11.1
